# Project information
site_name: oxd 2.4.4 Docs
site_description: Documentation for oxd OpenID Connect and UMA client software

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: sources
repo_name: GluuFederation/docs-oxd-prod
repo_url: https://github.com/GluuFederation/docs-oxd-prod/
edit_uri: edit/2.4.4/2.4.4/sources

# Configuration
theme: 
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '2.4.4'

# Tracking
google_analytics:
  - 'UA-31008645-7'
  - 'auto'
  
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite     
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '2.4.4': 'https://gluu.org/docs/oxd/2.4.4/'
    - '4.0 Beta': 'https://gluu.org/docs/oxd/4.0/'    
    - '3.1.4': 'https://gluu.org/docs/oxd/3.1.4/'
    - '3.1.3.1': 'https://gluu.org/docs/oxd/3.1.3.1/'
    - '3.1.3': 'https://gluu.org/docs/oxd/3.1.3/'
    - '3.1.2': 'https://gluu.org/docs/oxd/3.1.2/'
    - '3.1.1': 'https://gluu.org/docs/oxd/3.1.1/'
    - '3.0.1': 'https://gluu.org/docs/oxd/3.0.1/'
- ' ': 'https:/gluu.org/docs'
- ' ': 'https:/gluu.org/docs'
- Home: 'index.md'
# Protocol
- oxd Server:
    - 'Protocol': 'protocol/index.md'
    - 'Installation': 'install/index.md'
    - 'Configuration': 'conf/index.md'
    - 'Logs': 'logs/index.md'
# 3.0.0
- Libraries:
    - 'oxd API Client Libraries': 'libraries/api-client-libraries.md'
    - 'Python': 'libraries/python/index.md'
    - 'Java': 'libraries/java/index.md'
    - 'PHP':  'libraries/php/index.md'
    - 'Node': 'libraries/node/index.md'
    - 'Ruby': 'libraries/ruby/index.md'
    - 'CSharp': 'libraries/csharp/index.md'
    - 'Perl': 'libraries/perl/index.md'

- Plugins:
    - 'Wordpress': 'plugin/wordpress/index.md'
    - 'Magento': 'plugin/magento/index.md'
    - 'Drupal': 'plugin/drupal/index.md'
    - 'OpenCart': 'plugin/opencart/index.md'
    - 'SugarCRM': 'plugin/sugarcrm/index.md'
    - 'SuiteCRM': 'plugin/suitecrm/index.md'
    - 'RoundCube': 'plugin/roundcube/index.md'
    - 'Shopify': 'plugin/shopify/index.md'
    - 'NextCloud': 'plugin/nextcloud/index.md'
- Framework:
    - 'Java Spring': 'framework/spring/index.md'
    - 'Java Play Framework': 'framework/play/index.md'
    - 'Ruby on Rails': 'framework/rails/index.md'
    - 'Python Flask': 'framework/flask/index.md'
    - 'Node/Express': 'framework/node/index.md'
    - '.Net': 'framework/net/index.md'

# master docs
# - [install/index.md, hidden, hidden]
# - [conf/index.md, hidden, hidden]
# - [logs/index.md, hidden, hidden]
# - [libraries/api-client-libraries.md, hidden, hidden]
# - [libraries/python/index.md, hidden, hidden]
# - [libraries/java/index.md, hidden, hidden]
# - [libraries/php/index.md, hidden, hidden]
# - [libraries/node/index.md, hidden, hidden]
# - [libraries/ruby/index.md, hidden, hidden]
# - [libraries/csharp/index.md, hidden, hidden]
# - [libraries/perl/index.md, hidden, hidden]
# - [plugin/wordpress/index.md, hidden, hidden]
# - [plugin/magento/index.md, hidden, hidden]
# - [plugin/drupal/index.md, hidden, hidden]
# - [plugin/opencart/index.md, hidden, hidden]
# - [plugin/sugarcrm/index.md, hidden, hidden]
# - [plugin/suitecrm/index.md, hidden, hidden]
# - [plugin/roundcube/index.md, hidden, hidden]
# - [plugin/nextcloud/index.md, hidden, hidden]
# - [framework/spring/index.md, hidden, hidden]
# - [framework/play/index.md, hidden, hidden]
# - [framework/ruby/index.md, hidden, hidden]
# - [framework/python/index.md, hidden, hidden]
# - [framework/node/index.md, hidden, hidden]
