site_name: oxd Docs
site_description: Documenation for oxd OpenID Connect and UMA client software
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2017, Gluu, Inc.
docs_dir: sources 
repo_url: https://github.com/GluuFederation/docs-oxd-prod/tree/3.1.1/3.1.1
#theme: readthedocs
theme_dir: theme/material/
extra:
    version: '3.1.1'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Release Notes: 'release-notes/index.md'
- License: 'license/index.md'
- 'Installation': 'install/index.md'
- 'Configuration': 'configuration/index.md'
- 'Log Configuration': 'logs/index.md'
- 'API': 'api/index.md'
- oxd-https-extension:
  - 'Installation': 'oxd-https/install/index.md'
  - 'Configuration': 'oxd-https/configuration/index.md'
  - 'Log configuration': 'oxd-https/logs/index.md'
  - 'API': 'oxd-https/api/index.md'
- Native Libraries:
    - 'Overview-oxd API Client Libraries': 'libraries/api-client-libraries.md'
    - Languages:
        - 'Python': 'libraries/python/index.md'
        - 'Java': 'libraries/java/index.md'
        - 'PHP':  'libraries/php/index.md'
        - 'Node': 'libraries/node/index.md'
        - 'Ruby': 'libraries/ruby/index.md'
        - 'CSharp': 'libraries/csharp/index.md'
        - 'Perl': 'libraries/perl/index.md'
        - 'Go': 'libraries/golang/index.md'
    - Framework:
        - 'Java Spring': 'framework/spring/index.md'
        - 'Java Play Framework': 'framework/play/index.md'
        - 'Ruby on Rails': 'framework/rails/index.md'
        - 'Python Flask': 'framework/flask/index.md'
        - 'Node/Express': 'framework/node/index.md'
        - '.Net': 'framework/net/index.md'
- Plugins:
    - 'Wordpress': 'plugin/wordpress/index.md'
    - 'Magento': 'plugin/magento/index.md'
    - 'Drupal': 'plugin/drupal/index.md'
    - 'OpenCart': 'plugin/opencart/index.md'
    - 'SugarCRM': 'plugin/sugarcrm/index.md'
    - 'SuiteCRM': 'plugin/suitecrm/index.md'
    - 'RoundCube': 'plugin/roundcube/index.md'
    - 'Shopify': 'plugin/shopify/index.md'
    - 'NextCloud': 'plugin/nextcloud/index.md'
