site_name: oxd Docs
site_description: Documenation for oxd OpenID Connect and UMA client software
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2017, Gluu, Inc.
docs_dir: sources 
repo_url: https://github.com/GluuFederation/docs-oxd-prod/tree/3.1.1/3.1.1
#theme: readthedocs
theme_dir: theme/material/
extra:
    version: '3.1.1'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Release Notes: 'release-notes/index.md'
- Whats new in 3.1.x: '3.1.x-intro.md'
- License: 
    - 'License': 'license/index.md'
    - Authentication:
      - Signup: 'license/auth/signup/index.md'
      - Login: 'license/auth/login/index.md'
    - Account Dashboard: 'license/dashboard/index.md'
    - Account Profile: 'license/profile/index.md'
    - Payments and Credit Card Information:
      - Card List: 'license/payments/dashboard/index.md'
      - Add Card: 'license/payments/add/index.md'
      - Card Management: 'license/payments/primary/index.md'
    - Billing: 'license/billing/index.md'
- 'Install': 'install/index.md'
- 'Upgrade': 'upgrade/index.md'
- 'Configuration': 'configuration/index.md'
- 'Logs': 'logs/index.md'
- 'API': 'api/index.md'
- oxd-https-extension:
  - 'Start': 'oxd-https/start/index.md'
  - 'Configuration': 'oxd-https/configuration/index.md'
  - 'Logs': 'oxd-https/logs/index.md'
  - 'API': 'oxd-https/api/index.md'
- Libraries:
    - 'Overview': 'libraries/api-client-libraries.md'
    - Languages:
        - 'Python': 'libraries/python/index.md'
        - 'Java': 'libraries/java/index.md'
        - 'PHP':  'libraries/php/index.md'
        - 'Node': 'libraries/node/index.md'
        - 'Ruby': 'libraries/ruby/index.md'
        - 'CSharp': 'libraries/csharp/index.md'
        - 'Perl': 'libraries/perl/index.md'
        - 'Go': 'libraries/golang/index.md'
    - Frameworks:
        - 'Java Spring': 'framework/spring/index.md'
#       - 'Java Play Framework': 'framework/play/index.md'
        - 'Ruby on Rails': 'framework/rails/index.md'
        - 'Python Flask': 'framework/flask/index.md'
        - 'Node/Express': 'framework/node/index.md'
        - '.NET': 'framework/net/index.md'
- Plugins:
    - 'Wordpress': 'plugin/wordpress/index.md'
    - 'Magento': 'plugin/magento/index.md'
    - 'Drupal': 'plugin/drupal/index.md'
    - 'OpenCart': 'plugin/opencart/index.md'
    - 'SugarCRM': 'plugin/sugarcrm/index.md'
    - 'SuiteCRM': 'plugin/suitecrm/index.md'
    - 'RoundCube': 'plugin/roundcube/index.md'
    - 'Shopify': 'plugin/shopify/index.md'
    - 'NextCloud': 'plugin/nextcloud/index.md'
