# Project information
site_name: oxd Docs
site_description: Documentation for oxd OpenID Connect and UMA client software
site_favicon: 'favicon.ico'

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: sources
#repo_name: GluuFederation/docs-oxd-prod
repo_url: https://github.com/GluuFederation/docs-oxd-prod/tree/3.1.4/3.1.4
#repo_url: https://github.com/GluuFederation/docs-oxd-prod/
#edit_uri: edit/3.1.4/3.1.4/sources

# Configuration
theme_dir: theme/material
#theme: 
#    name: material
#    palette:
#        primary: 'green'
#        accent: 'green'
#    logo: 'gluu.jpg'
#    favicon: 'favicon.ico'
extra:
    version: '3.1.4'
    logo: 'gluu.png'
    
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
#- codehilite     
- pymdownx.superfences

# Navigation
#nav:
#- 'Versions':
#    - '3.1.4': 'https://gluu.org/docs/oxd/3.1.4/'
#    - '3.1.3.1': 'https://gluu.org/docs/oxd/3.1.3.1/'
#    - '3.1.3': 'https://gluu.org/docs/oxd/3.1.3/'
#    - '3.1.2': 'https://gluu.org/docs/oxd/3.1.2/'
#    - '3.1.1': 'https://gluu.org/docs/oxd/3.1.1/'
#    - '3.0.1': 'https://gluu.org/docs/oxd/3.0.1/'
#    - '2.4.4': 'https://gluu.org/docs/oxd/2.4.4/'
#- ' ': 'https:/gluu.org/docs'
#- ' ': 'https:/gluu.org/docs'
pages:
- Home: 'index.md'
- Release Notes: 'release-notes/index.md'
- Whats new in 3.1.x: '3.1.x-intro.md'
- 'Install': 'install/index.md'
- 'Upgrade': 'upgrade/index.md'
- 'Service Operations': 'operations/index.md'
- 'Configuration': 'configuration/index.md'
- 'Logs': 'logs/index.md'
- 'API': 'api/index.md'
- 'FAQ': 'faq/index.md'
- oxd-https-extension:
  - 'Start ': 'oxd-https/start/index.md'
  - 'Configuration': 'oxd-https/configuration/index.md'
  - 'Logs': 'oxd-https/logs/index.md'
  - 'API': 'oxd-https/api/index.md'
  - 'Security Considerations': 'oxd-https/security/index.md'
- Libraries:
    - 'Overview': 'libraries/api-client-libraries.md'
    - Languages:
        - 'Python': 'libraries/languages/python/index.md'
        - 'Java': 'libraries/languages/java/index.md'
        - 'PHP':  'libraries/languages/php/index.md'
        - 'Node': 'libraries/languages/node/index.md'
        - 'Ruby': 'libraries/languages/ruby/index.md'
        - 'CSharp': 'libraries/languages/csharp/index.md'
        - 'Perl': 'libraries/languages/perl/index.md'
        #- 'Go': 'libraries/languages/go/index.md'
    - Frameworks:
        - 'Java Spring': 'libraries/framework/spring/index.md'
 #       - 'Java Play Framework': 'libraries/framework/play/index.md'
        #- 'Ruby on Rails': 'libraries/framework/rails/index.md'
        - 'Python Flask': 'libraries/framework/flask/index.md'
        - 'Express': 'libraries/framework/express/index.md'
        - '.NET': 'libraries/framework/net/index.md'
- Plugins:
    - 'Wordpress': 'plugin/wordpress/index.md'
    - 'Magento': 'plugin/magento/index.md'
    - 'Drupal': 'plugin/drupal/index.md'
    - 'OpenCart': 'plugin/opencart/index.md'
    - 'SugarCRM': 'plugin/sugarcrm/index.md'
    - 'SuiteCRM': 'plugin/suitecrm/index.md'
    - 'RoundCube': 'plugin/roundcube/index.md'
    - 'Shopify': 'plugin/shopify/index.md'
    - 'NextCloud': 'plugin/nextcloud/index.md'
