# Project information
site_name: oxd 4.0 Docs
site_description: Documentation for oxd OpenID Connect and UMA client software
site_favicon: 'favicon.ico'

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs-oxd-prod/tree/4.0/docs

# Configuration
theme_dir: theme/material
#theme: 
#    name: material
#    palette:
#        primary: 'green'
#        accent: 'green'
#    logo: 'gluu.jpg'
#    favicon: 'favicon.ico'
extra:
    version: '4.0'
    logo: 'gluu.png'
    
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite     
- pymdownx.superfences
#extra_css: 
#    - 'swagger/swagger-ui.css'
#extra_javascript: 
#    - 'swagger/swagger-ui-bundle.js'
#    - 'swagger/swagger-ui-standalone-preset.js'
#    - 'swagger/swagger-ui.js'

# Navigation
#nav:
#- 'Versions':
#    - '4.0': 'https://gluu.org/docs/oxd/4.0/'
#    - '3.1.4': 'https://gluu.org/docs/oxd/3.1.4/'
#    - '3.1.3.1': 'https://gluu.org/docs/oxd/3.1.3.1/'
#    - '3.1.3': 'https://gluu.org/docs/oxd/3.1.3/'
#    - '3.1.2': 'https://gluu.org/docs/oxd/3.1.2/'
#    - '3.1.1': 'https://gluu.org/docs/oxd/3.1.1/'
#    - '3.0.1': 'https://gluu.org/docs/oxd/3.0.1/'
#    - '2.4.4': 'https://gluu.org/docs/oxd/2.4.4/'
#- ' ': 'https:/gluu.org/docs'
#- ' ': 'https:/gluu.org/docs'
pages:
- Home: 'index.md'
- Release Notes: 'release-notes/index.md'
- Whats new in 4.x: '4.x-intro.md'
- 'Install & Run': 'install/index.md'
- 'Tutorial': 'tutorial/index.md'
- 'Upgrade': 'upgrade/index.md'
- 'Configuration': 'configuration/index.md'
- 'Logs': 'logs/index.md'
- 'API': 'api/index.md'
- 'Security Considerations': 'security/index.md'
- 'FAQ': 'faq/index.md'
