# Project information
site_name: oxd 4.1 Docs
site_description: Documentation for oxd OpenID Connect and UMA client software

# Copyright
copyright: Copyright &copy; 2020, Gluu, Inc.

# Repository
docs_dir: sources
repo_name: GluuFederation/docs-oxd-prod
repo_url: https://github.com/GluuFederation/docs-oxd-prod/
edit_uri: edit/4.1/docs/sources

# Configuration
theme: 
    name: material
    custom_dir: 'theme'
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '4.1'

# Tracking
google_analytics:
  - 'UA-31008645-7'
  - 'auto'
  
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite     
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '4.1': 'https://gluu.org/docs/oxd/4.1/'
    - '4.0': 'https://gluu.org/docs/oxd/4.0/'
    - '3.1.4': 'https://gluu.org/docs/oxd/3.1.4/'
    - '3.1.3.1': 'https://gluu.org/docs/oxd/3.1.3.1/'
    - '3.1.3': 'https://gluu.org/docs/oxd/3.1.3/'
    - '3.1.2': 'https://gluu.org/docs/oxd/3.1.2/'
    - '3.1.1': 'https://gluu.org/docs/oxd/3.1.1/'
    - 'EOL versions': 'https://gluu.org/docs/eol'
- ' ': 'https:/gluu.org/docs'
- ' ': 'https:/gluu.org/docs'
- Home: 'index.md'
- Release Notes: 'release-notes/index.md'
- Whats new in 4.x: '4.x-intro.md'
- 'Install & Run': 'install/index.md'
- Tutorials: 
        - 'Python': './tutorials/python/index.md'
        - 'Java': './tutorials/java/index.md'
        - 'Spring': './tutorials/spring/index.md'
- 'Upgrade': 'upgrade/index.md'
- Configuration: 
        - 'Configuration': './configuration/oxd-configuration/index.md'
        - 'H2': './configuration/h2/index.md'
        - 'Redis': './configuration/redis/index.md'
- 'Logs': 'logs/index.md'
- 'API': 'api/index.md'
- 'Security Considerations': 'security/index.md'
- 'Tracing': 'tracing/index.md'
- 'FAQ': 'faq/index.md'
