site_name: oxd Docs
site_description: Documentation for oxd OpenID Connect and UMA client software
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2018, Gluu, Inc.
docs_dir: sources 
repo_url: https://github.com/GluuFederation/docs-oxd-prod/tree/4.0.beta/docs
#theme: readthedocs
theme_dir: theme/material/
extra:
    version: '4.0.beta'
    logo: 'gluu.png'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Release Notes: 'release-notes/index.md'
- Whats new in 4.x: '3.1.x-intro.md'
- 'Install & Run': 'install/index.md'
- 'Tutorial': 'tutorial/index.md'
- 'Upgrade': 'upgrade/index.md'
- 'Configuration': 'configuration/index.md'
- 'Logs': 'logs/index.md'
- 'API': 'api/index.md'
- 'Security Considerations': 'security/index.md'
- 'FAQ': 'faq/index.md'
